services:
  database:
    image: postgres:15
    container_name: my_database
    restart: always
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: sahil@222
      POSTGRES_DB: meta-data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://sahil:sahil@222@database:5432/meta-data" # Database connection string
    depends_on:
      - database

volumes:
  db_data:
