FROM node:20-alpine AS builder

WORKDIR /app

COPY pnpm-lock.yaml package.json ./

RUN npm install -g pnpm && pnpm install

COPY ./apps/frontend ./apps/frontend

COPY ./apps/frontend/vite.config.ts ./apps/frontend/vite.config.ts

WORKDIR /app/apps/frontend
RUN pnpm install

RUN pnpm build

FROM node:20-alpine AS runner

WORKDIR /app
RUN npm install -g pnpm

EXPOSE 5173

COPY --from=builder /app/apps/frontend/dist /app/apps/frontend/dist
COPY --from=builder /app/package.json /app/package.json


RUN ls
CMD ["npm", "run", "start:frontend"]
